{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Demo for VirtualCity\n",
    "##### This is a demo of how to interact with VirtualCity. The demo will walk though how to start an environment and control it, how to prepare it to perform activities and finally how to perform activities in them."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Setup\n",
    "##### The first step is to start a communication with the simulator. Make sure before you run this notebook, that you have downloaded the correct version of the environment for your OS and your drivers and OS is updated to the latest version."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "##### Install required packages"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "!pip install python-socketio\n",
    "!pip install \"python-socketio[client]\"\n",
    "!pip install eventlet"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### Communication server\n",
    "##### This code is only run once to initialize the server. Run the following server code on a separate process (you can use a tmux server to run the code but avoid running it within the Jupyter Notebook file)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import socketio\n",
    "import eventlet\n",
    "\n",
    "sio = socketio.Server()\n",
    "app = socketio.WSGIApp(sio)\n",
    "\n",
    "clients = []\n",
    "\n",
    "@sio.event\n",
    "def connect(sid, environ):\n",
    "    print('Client connected:', sid)\n",
    "    clients.append(sid)\n",
    "\n",
    "@sio.event\n",
    "def disconnect(sid):\n",
    "    print('Client disconnected:', sid)\n",
    "    if sid in clients:\n",
    "        clients.remove(sid)\n",
    "\n",
    "@sio.event\n",
    "def message(sid, data):\n",
    "    sio.emit('message', data)\n",
    "\n",
    "@sio.event\n",
    "def graph(sid, data):\n",
    "    sio.emit('graph', data)\n",
    "\n",
    "@sio.event\n",
    "def make(sid, data):\n",
    "    sio.emit('make', data)\n",
    "\n",
    "@sio.event\n",
    "def reset(sid, data):\n",
    "    sio.emit('reset', data)\n",
    "\n",
    "@sio.event\n",
    "def observation(sid, data):\n",
    "    sio.emit('observation', data)\n",
    "\n",
    "@sio.event\n",
    "def set_action(sid, data):\n",
    "    sio.emit('set_action', data)\n",
    "\n",
    "@sio.event\n",
    "def system_agent(sid, data):\n",
    "    sio.emit('system_agent', data)\n",
    "\n",
    "@sio.event\n",
    "def render(sid, data):\n",
    "    sio.emit('render', data)\n",
    "\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    eventlet.wsgi.server(eventlet.listen(('0.0.0.0', 5000)), app)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "##### This code intializes the client communcation. It allows you to send commands to the server that you previously setup, which acts as a bridge between the executable file and the jupyter notebook. Run the following code to intialize the client communication with the environment"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Connected to server\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-84 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"e:\\conda\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    return handler(*args)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Hunter\\AppData\\Local\\Temp\\ipykernel_29568\\2541722284.py\", line 18, in message\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Exception in thread Thread-88 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"e:\\conda\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    return handler(*args)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Hunter\\AppData\\Local\\Temp\\ipykernel_29568\\2541722284.py\", line 18, in message\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Exception in thread Thread-90 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"e:\\conda\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    return handler(*args)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Hunter\\AppData\\Local\\Temp\\ipykernel_29568\\2541722284.py\", line 18, in message\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Exception in thread Thread-99 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-100 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"e:\\conda\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"e:\\conda\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1010, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    return handler(*args)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Hunter\\AppData\\Local\\Temp\\ipykernel_29568\\2541722284.py\", line 18, in message\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\decoder.py\", line 337, in decode\n",
      "    return handler(*args)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Hunter\\AppData\\Local\\Temp\\ipykernel_29568\\2541722284.py\", line 18, in message\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Exception in thread Thread-109 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"e:\\conda\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    return handler(*args)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Hunter\\AppData\\Local\\Temp\\ipykernel_29568\\2541722284.py\", line 18, in message\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\decoder.py\", line 340, in decode\n",
      "    raise JSONDecodeError(\"Extra data\", s, end)\n",
      "json.decoder.JSONDecodeError: Extra data: line 6 column 6 (char 89)\n",
      "Exception in thread Thread-117 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"e:\\conda\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    return handler(*args)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Hunter\\AppData\\Local\\Temp\\ipykernel_29568\\2541722284.py\", line 18, in message\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Exception in thread Thread-122 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"e:\\conda\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    return handler(*args)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Hunter\\AppData\\Local\\Temp\\ipykernel_29568\\2541722284.py\", line 18, in message\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Exception in thread Thread-127 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"e:\\conda\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    return handler(*args)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Hunter\\AppData\\Local\\Temp\\ipykernel_29568\\2541722284.py\", line 18, in message\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Exception in thread Thread-138 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"e:\\conda\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    return handler(*args)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Hunter\\AppData\\Local\\Temp\\ipykernel_29568\\2541722284.py\", line 18, in message\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Exception in thread Thread-152 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"e:\\conda\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    return handler(*args)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Hunter\\AppData\\Local\\Temp\\ipykernel_29568\\2541722284.py\", line 18, in message\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\decoder.py\", line 340, in decode\n",
      "    raise JSONDecodeError(\"Extra data\", s, end)\n",
      "json.decoder.JSONDecodeError: Extra data: line 6 column 2 (char 85)\n",
      "Exception in thread Thread-155 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"e:\\conda\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    return handler(*args)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Hunter\\AppData\\Local\\Temp\\ipykernel_29568\\2541722284.py\", line 18, in message\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\decoder.py\", line 340, in decode\n",
      "    raise JSONDecodeError(\"Extra data\", s, end)\n",
      "json.decoder.JSONDecodeError: Extra data: line 6 column 6 (char 89)\n",
      "Exception in thread Thread-164 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"e:\\conda\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    return handler(*args)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Hunter\\AppData\\Local\\Temp\\ipykernel_29568\\2541722284.py\", line 18, in message\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Exception in thread Thread-178 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"e:\\conda\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    return handler(*args)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Hunter\\AppData\\Local\\Temp\\ipykernel_29568\\2541722284.py\", line 18, in message\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Exception in thread Thread-204 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"e:\\conda\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    return handler(*args)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Hunter\\AppData\\Local\\Temp\\ipykernel_29568\\2541722284.py\", line 18, in message\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Exception in thread Thread-205 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"e:\\conda\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    return handler(*args)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Hunter\\AppData\\Local\\Temp\\ipykernel_29568\\2541722284.py\", line 18, in message\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Exception in thread Thread-217 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"e:\\conda\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    return handler(*args)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Hunter\\AppData\\Local\\Temp\\ipykernel_29568\\2541722284.py\", line 18, in message\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Exception in thread Thread-223 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"e:\\conda\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "Exception in thread Thread-224 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "    _threading_Thread_run(self)\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1010, in run\n",
      "    self.run()\n",
      "  File \"e:\\conda\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    _threading_Thread_run(self)\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1010, in run\n",
      "    self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    return handler(*args)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Hunter\\AppData\\Local\\Temp\\ipykernel_29568\\2541722284.py\", line 18, in message\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    return handler(*args)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Hunter\\AppData\\Local\\Temp\\ipykernel_29568\\2541722284.py\", line 18, in message\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 293, in load\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 346, in loads\n",
      "    return loads(fp.read(),\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\decoder.py\", line 340, in decode\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\decoder.py\", line 340, in decode\n",
      "    raise JSONDecodeError(\"Extra data\", s, end)\n",
      "json.decoder.JSONDecodeError: Extra data: line 6 column 2 (char 85)\n",
      "    raise JSONDecodeError(\"Extra data\", s, end)\n",
      "json.decoder.JSONDecodeError: Extra data: line 6 column 2 (char 85)\n",
      "Exception in thread Thread-235 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"e:\\conda\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    return handler(*args)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Hunter\\AppData\\Local\\Temp\\ipykernel_29568\\2541722284.py\", line 18, in message\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Exception in thread Thread-242 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"e:\\conda\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    return handler(*args)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Hunter\\AppData\\Local\\Temp\\ipykernel_29568\\2541722284.py\", line 18, in message\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Exception in thread Thread-245 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"e:\\conda\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    return handler(*args)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Hunter\\AppData\\Local\\Temp\\ipykernel_29568\\2541722284.py\", line 18, in message\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Exception in thread Thread-253 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"e:\\conda\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    return handler(*args)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Hunter\\AppData\\Local\\Temp\\ipykernel_29568\\2541722284.py\", line 18, in message\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Exception in thread Thread-274 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"e:\\conda\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    return handler(*args)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Hunter\\AppData\\Local\\Temp\\ipykernel_29568\\2541722284.py\", line 18, in message\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Exception in thread Thread-276 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"e:\\conda\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    return handler(*args)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Hunter\\AppData\\Local\\Temp\\ipykernel_29568\\2541722284.py\", line 18, in message\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Exception in thread Thread-308 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"e:\\conda\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    return handler(*args)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Hunter\\AppData\\Local\\Temp\\ipykernel_29568\\2541722284.py\", line 18, in message\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Exception in thread Thread-321 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"e:\\conda\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    return handler(*args)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Hunter\\AppData\\Local\\Temp\\ipykernel_29568\\2541722284.py\", line 18, in message\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Exception in thread Thread-326 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"e:\\conda\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    return handler(*args)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Hunter\\AppData\\Local\\Temp\\ipykernel_29568\\2541722284.py\", line 18, in message\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\decoder.py\", line 340, in decode\n",
      "    raise JSONDecodeError(\"Extra data\", s, end)\n",
      "json.decoder.JSONDecodeError: Extra data: line 6 column 4 (char 109)\n",
      "Exception in thread Thread-332 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"e:\\conda\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    return handler(*args)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Hunter\\AppData\\Local\\Temp\\ipykernel_29568\\2541722284.py\", line 18, in message\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Exception in thread Thread-343 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"e:\\conda\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    return handler(*args)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Hunter\\AppData\\Local\\Temp\\ipykernel_29568\\2541722284.py\", line 18, in message\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Exception in thread Thread-348 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"e:\\conda\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    return handler(*args)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Hunter\\AppData\\Local\\Temp\\ipykernel_29568\\2541722284.py\", line 18, in message\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\decoder.py\", line 340, in decode\n",
      "    raise JSONDecodeError(\"Extra data\", s, end)\n",
      "json.decoder.JSONDecodeError: Extra data: line 6 column 6 (char 89)\n",
      "Exception in thread Thread-354 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"e:\\conda\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    return handler(*args)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Hunter\\AppData\\Local\\Temp\\ipykernel_29568\\2541722284.py\", line 18, in message\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Exception in thread Thread-359 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"e:\\conda\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    return handler(*args)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Hunter\\AppData\\Local\\Temp\\ipykernel_29568\\2541722284.py\", line 18, in message\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\decoder.py\", line 340, in decode\n",
      "    raise JSONDecodeError(\"Extra data\", s, end)\n",
      "json.decoder.JSONDecodeError: Extra data: line 6 column 6 (char 89)\n",
      "Exception in thread Thread-366 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"e:\\conda\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    return handler(*args)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Hunter\\AppData\\Local\\Temp\\ipykernel_29568\\2541722284.py\", line 18, in message\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Exception in thread Thread-386 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"e:\\conda\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    return handler(*args)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Hunter\\AppData\\Local\\Temp\\ipykernel_29568\\2541722284.py\", line 18, in message\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Exception in thread Thread-421 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"e:\\conda\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    return handler(*args)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Hunter\\AppData\\Local\\Temp\\ipykernel_29568\\2541722284.py\", line 18, in message\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Exception in thread Thread-464 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"e:\\conda\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    return handler(*args)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Hunter\\AppData\\Local\\Temp\\ipykernel_29568\\2541722284.py\", line 18, in message\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Exception in thread Thread-487 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"e:\\conda\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    return handler(*args)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Hunter\\AppData\\Local\\Temp\\ipykernel_29568\\2541722284.py\", line 18, in message\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Exception in thread Thread-523 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"e:\\conda\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"e:\\conda\\Lib\\threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    return handler(*args)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Hunter\\AppData\\Local\\Temp\\ipykernel_29568\\2541722284.py\", line 18, in message\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"e:\\conda\\Lib\\json\\decoder.py\", line 340, in decode\n",
      "    raise JSONDecodeError(\"Extra data\", s, end)\n",
      "json.decoder.JSONDecodeError: Extra data: line 50 column 2 (char 1042)\n"
     ]
    }
   ],
   "source": [
    "import socketio\n",
    "import json\n",
    "\n",
    "sio = socketio.Client()\n",
    "\n",
    "@sio.event\n",
    "def connect():\n",
    "    print(\"Connected to server\")\n",
    "\n",
    "@sio.event\n",
    "def disconnect():\n",
    "    print(\"Disconnected from server\")\n",
    "\n",
    "@sio.event\n",
    "def message(data):\n",
    "    try:\n",
    "        with open(\"message.json\", \"r\") as f:\n",
    "            message = json.load(f)\n",
    "    except FileNotFoundError:\n",
    "        message = []\n",
    "\n",
    "    message.append(data)\n",
    "    \n",
    "    with open(\"message.json\", \"w\") as f:\n",
    "        json.dump(message, f, indent=4)\n",
    "\n",
    "@sio.event\n",
    "def graph(data):\n",
    "    with open(\"graph.json\", \"w\") as f:\n",
    "        json.dump(data, f, indent=4)\n",
    "\n",
    "\n",
    "def make(data):\n",
    "    sio.emit('make', data)\n",
    "\n",
    "def reset(data):\n",
    "    sio.emit('reset', data)\n",
    "\n",
    "def observation(data):\n",
    "    sio.emit('observation', data)\n",
    "\n",
    "def set_action(data):\n",
    "    sio.emit('set_action', data)\n",
    "\n",
    "def system_agent(data):\n",
    "    sio.emit('system_agent', data)\n",
    "\n",
    "def render(data):\n",
    "    sio.emit('render', data)\n",
    "\n",
    "\n",
    "sio.connect('http://localhost:5000')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Sending commands to the environment\n",
    "##### When you want to start a environment or send a instruction to an agent, etc. You will need to pack the configuration in a dictionary and use the emit function to send the command to the environment. If the command was succesfully executed in the environment, you will recieve a message: {success: True} and if it failed then you will recieve a message: {success: False}. "
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Make a environment\n",
    "##### To start a environment, you need to provide the environment name that you want to initialize. You can select from various pre-built environments or use the \"Procedural Generation\" argument with a seed to create or recreate a previously generated environment on the fly."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "\"\"\"\n",
    "Args:\n",
    "    environment (str): The name of the environment. Default is 'Demo'.\n",
    "    num_env (list): The number of environments. Default is [1].\n",
    "\"\"\"\n",
    "data = {\n",
    "    \"environment\": \"WatchAndHelp1\", \n",
    "    # \"num_env\": [1]\n",
    "}\n",
    "\n",
    "make(data)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Create a graph observation\n",
    "##### You can create a environment graph that describes the entire environment in a JSON file. The graph contains object information, relations, states, etc."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "\"\"\"\n",
    "Args:\n",
    "    type (str): The type of observation. Default is 'graph'.\n",
    "    radius (list): The radius of the observation. Default is [-1].\n",
    "\"\"\"\n",
    "data = {\n",
    "    \"type\": \"full\", \n",
    "    # \"radius\": [-1]\n",
    "}\n",
    "\n",
    "observation(data)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Reset the environment\n",
    "##### To reset a environment, you can choose to provide a environment graph to reset it to a previosly saved state. If no graph is provided, then the environment is reset to its default state. "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "\"\"\"\n",
    "Args:\n",
    "    env_index (list): The index of the environment. Default is [0].\n",
    "    graph (dict): The environment graph in JSON. Default is None.\n",
    "\"\"\"\n",
    "import json\n",
    "\n",
    "with open(\"graph.json\", \"r\") as f:\n",
    "    graph = json.load(f)\n",
    "\n",
    "data = {\n",
    "    \"env_index\": [0], \n",
    "    \"graph\": graph\n",
    "}\n",
    "\n",
    "reset(data)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Set action for an agent\n",
    "##### To send a action command to a agent, you can use provide a list containing the agent index, and a list describing the task which needs to be completed. The task list is structured in the following way: [action, object_1, relation, object_2]. To select a action with the appropriate object and relation, you can refer to the docs."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "import time\n",
    "\"\"\"\n",
    "Args:\n",
    "    agent_index (list): The index of the agent. Default is [0].\n",
    "    task (list): The task assigned to the agent. Default is [0, 0, 0, 0].\n",
    "    coordinate (list): The coordinate of the agent. Default is [0, 0, 0].\n",
    "\"\"\"\n",
    "data = {\n",
    "    \"agent_index\": [1],\n",
    "    \"task\": [1, 25, 0, 0],\n",
    "    # \"coordinate\": [1,1,0]\n",
    "}\n",
    "\n",
    "data0 ={'agent_index': [1], 'task': [6, 326, 0, 0]}\n",
    "\n",
    "data1 ={'agent_index': [0], 'task': [6, 326, 0, 0]}\n",
    "\n",
    "data2 ={'agent_index': [0], 'task': [1, 300, 0, 0]}\n",
    "\n",
    "data3 ={'agent_index': [0], 'task': [8, 326, 300, 0]}\n",
    "\n",
    "data4 ={'agent_index': [0], 'task': [1, 335, 0, 0]}\n",
    "\n",
    "data5 ={'agent_index': [0], 'task': [6, 335, 0, 0]}\n",
    "\n",
    "data6 ={'agent_index': [0], 'task': [1, 305, 0, 0]}\n",
    "\n",
    "data7 ={'agent_index': [0], 'task': [8, 335, 305, 0]}\n",
    "\n",
    "datas = [data0, data1, data2, data3, data4, data5, data6, data7]\n",
    "\n",
    "set_action(data0)\n",
    "    \n",
    "    \n",
    "\n",
    "    \n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "##### A more interactive way is to create list of actions in natural language, and run it with the sequence function from the optional utils package. Try to follow a similar syntax as the example provided below when running your own unique scripts."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 70,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[{'agent_index': [1], 'task': [0, 1, 0, 0]},\n",
       " {'agent_index': [2], 'task': [0, 2, 0, 0]},\n",
       " {'agent_index': [3], 'task': [0, 4, 5, 1]},\n",
       " {'agent_index': [4], 'task': [0, 6, 0, 0]},\n",
       " {'agent_index': [5], 'task': [0, 3, 7, 2]},\n",
       " {'agent_index': [6], 'task': [1, 8, 0, 0]},\n",
       " {'agent_index': [7], 'task': [0, 10, 11, 1]}]"
      ]
     },
     "execution_count": 70,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import utils\n",
    "\n",
    "# Sequence\n",
    "action_list = [\n",
    "    \"agent_1 pickup object_1\",\n",
    "    \"agent_2 walk to object_2\",\n",
    "    \"agent_3 place object_4 on object_5\",\n",
    "    \"agent_4 jump over object_6\",\n",
    "    \"agent_5 examine object3 under object_7\",\n",
    "    \"agent_6 run from object_8 to object_9\",\n",
    "    \"agent_7 pick object_10 and place on object_11\",\n",
    "]\n",
    "\n",
    "utils.sequence(action_list)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Change system agent settings\n",
    "##### You can also enable or disable system agents within the environment. Additional settings such as crowd density, vehicle denisity, parked cars, etc. can be changed via the API"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [],
   "source": [
    "\"\"\"\n",
    "Args:\n",
    "    crowd (bool): The crowd data. Default is True.\n",
    "    traffic (bool): The traffic data. Default is True.\n",
    "    visualize (bool): Visualize crowd and traffic. Default is False\n",
    "\"\"\"\n",
    "data = {\n",
    "    \"crowd\": True, \n",
    "    \"traffic\": True,\n",
    "    \"visualize\": False,\n",
    "}\n",
    "system_agent(data)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Change rendering settings\n",
    "##### You can also change the rendering settings of the environment in real time such as the camera, resolution, fps, etc. "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [],
   "source": [
    "\"\"\"\n",
    "Args:\n",
    "    camera_index (list): The index of the camera. Default is [1].\n",
    "    render_pipeline (str): Which renderer to use. Default is raytracing.\n",
    "    image_width (list): The width of the image. Default is [1920].\n",
    "    image_height (list): The height of the image. Default is [1080].\n",
    "    fps (list): The frames per second. Default is [60].\n",
    "\"\"\"\n",
    "data = {\n",
    "    \"render_pipeline\": 'raytracing',\n",
    "    \"camera_index\": [1],\n",
    "    \"image_width\": [1920],\n",
    "    \"image_height\": [1080],\n",
    "    \"fps\": [60],\n",
    "    \"fov\": [90],\n",
    "}\n",
    "\n",
    "render(data)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "base",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
